const express = require('express');
const router = express.Router();
const { getAllTalents, getTalentById, getAllBrands } = require('../controllers/userController');
const { verifyFirebaseToken } = require('../middleware/authMiddleware');

router.use('/auth', require('../modules/auth/auth.routes'));
router.use('/users', require('./userRoutes'));
router.get('/talents', verifyFirebaseToken, getAllTalents);
router.get('/talents/:id', verifyFirebaseToken, getTalentById);
router.get('/brands', verifyFirebaseToken, getAllBrands);
// router.use('/talents', require('../modules/talents/talent.routes'));
router.use('/brands', require('../modules/brands/brand.routes'));
router.use('/campaigns', require('../modules/campaigns/campaign.routes'));
router.use('/applications', require('../modules/applications/application.routes'));
router.use('/invites', require('../modules/invites/invite.routes'));
router.use('/chat', require('../modules/chat/chat.routes'));
router.use('/payments', require('../modules/payments/payment.routes'));
router.use('/reviews', require('../modules/reviews/review.routes'));
router.use('/admin', require('../modules/admin/admin.routes'));
router.use('/notifications', require('../modules/notifications/notification.routes'));
router.use('/connections', require('../modules/connections/connection.routes'));
router.use('/', require('../modules/upload/upload.routes'));
router.use('/events', require('./eventRoutes'));
router.use('/stories', require('./storyRoutes'));
router.use('/posts', require('./feedPostRoutes'));
module.exports = router;
